something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180525003846-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180525002041-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180524002645-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180524001686-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180523003877-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180523001668-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180522002166-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180522002075-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180521001825-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180521001635-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180518003628-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180518003145-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180518002623-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180517001630-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180517000008-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180516003415-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180516002312-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180515003623-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180515003363-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180514003216-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180514002627-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180513001332-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180513000006-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180513000005-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180512002568-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180512002376-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180512002210-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180511002442-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180511002352-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180511002109-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180511001997-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180510004040-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180510002659-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180510002556-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180509004108-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180509002919-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180509001860-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180509001786-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180508003933-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180507003214-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180507003182-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180507001222-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180504003792-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180504003674-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180503001786-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180502001371-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180430001351-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180430001262-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180429000003-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180427003149-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180427002956-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180427002454-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180427002310-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180426004074-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180426003948-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180426002464-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180426001776-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180425002766-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180425002655-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=校園
title=法國調查陸間諜網 逮捕兩名前探員
site_url=http://campus.chinatimes.com/20180424003083-262301
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180529000002-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180529000002-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180529000002-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003810-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003810-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003810-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003804-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003804-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003804-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003833-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003833-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003833-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003788-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003788-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003788-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003815-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003815-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003815-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003716-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003716-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003716-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003656-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003656-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003656-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003673-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003673-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003673-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003711-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003711-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003711-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003596-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003596-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003596-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003507-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003507-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003507-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003501-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003501-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003501-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003500-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003500-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003500-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003430-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003430-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003430-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003415-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003415-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003415-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003395-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003395-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003395-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003379-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003379-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003379-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003375-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003375-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003375-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003373-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003373-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003373-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003232-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003232-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003232-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003267-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003267-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003267-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003283-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003283-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003283-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003313-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003313-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003313-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003317-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003317-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003317-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003116-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003116-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003116-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003093-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003093-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003093-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003070-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003070-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003070-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003055-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003055-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003055-260410?

something wrong in page1
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003038-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003038-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003038-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528003015-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528003015-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528003015-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002979-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002979-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002979-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002997-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002997-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002997-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002959-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002959-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002959-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002922-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002922-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002922-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002919-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002919-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002919-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528001650-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528001650-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528001650-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002820-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002820-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002820-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002746-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002746-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002746-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528001493-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528001493-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528001493-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528001923-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528001923-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528001923-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002330-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002330-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002330-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002577-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002577-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002577-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002557-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002557-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002557-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002291-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002291-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002291-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002299-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002299-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002299-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002238-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002238-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002238-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002220-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002220-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002220-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002172-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002172-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002172-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002164-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002164-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002164-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002153-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002153-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002153-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002090-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002090-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002090-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002066-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002066-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002066-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002048-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002048-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002048-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528002042-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528002042-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528002042-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528001965-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528001965-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528001965-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528001911-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528001911-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528001911-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528001882-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528001882-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528001882-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528001859-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528001859-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528001859-260410?

something wrong in page2
category=財經
title=提名成真？ 姚「期待好結果」
site_url=//www.chinatimes.com/realtimenews/20180528001720-260410
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 83, in <module>
    result = req.get(site_url).text
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\MCU\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.chinatimes.com/realtimenews/20180528001720-260410': No schema supplied. Perhaps you meant http:////www.chinatimes.com/realtimenews/20180528001720-260410?

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180528003546-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180528003497-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/delicacy/20180528003162-330502
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://girl.styletc.com/news/20180528003068-360104
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/movie-drama/20180528002971-330401
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/delicacy/20180528002877-330502
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/fitness/20180528002639-330204
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/people/20180525002334-330302
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/delicacy/20180524003795-330502
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/astrology/20180525003583-330602
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/fitness/20180524002180-330204
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/trend/20180528001168-330102
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/trend/20180528000972-330102
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180528000911-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180528000898-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180528000863-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180528000830-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/skincare/20180527001615-330202
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/perfume-nails/20180526002964-330205
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page1
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180525003832-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180525003731-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180525003718-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180525003701-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/relationship/20180525003681-330601
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/art-design/20180525003493-330404
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/astrology/20180525003324-330602
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/delicacy/20180525003273-330502
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/delicacy/20180525003013-330502
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/astrology/20180525003025-330602
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/deco/20180525002844-330504
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/deco/20180525002790-330504
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/astrology/20180525002714-330602
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/jewelry-watch/20180525002658-330104
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/car/20180525002537-330802
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/men-style/20180525002373-330801
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/travel/20180525002284-330503
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/skincare/20180525001761-330202
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/makeup-hair/20180525001681-330201
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/travel/20180523003643-330503
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

something wrong in page2
category=樂時尚
title=新平價iPad台灣悄悄開賣 可搭Apple Pencil媲美頂級款
site_url=http://www.styletc.com/fitness/20180523003271-330204
Traceback (most recent call last):
  File "D:\xampp\htdocs\project\PublicOpinion\PyCrawler\ChinatimesCrawler.py", line 86, in <module>
    title = soup.select('hgroup h1')[0].text.strip()
IndexError: list index out of range

